### PR TITLE
Feature/comment lines

### PR DESCRIPTION
**Pull request by FaBjE**
Hello,

While making a "script" to control a BLE LED Strip I noticed there was no way to put a comment in the file.
Or that empty lines would cause the "script" execution to be aborted.

I've added the functionality so that:
- Lines can be commented by `//`
- Empty lines are not causing the end of execution, just skipped
- The end of "script" file is still detected

After my changes I've updated the readme.md with my changes and "lined up" the documentation with the improvements made in the meantime.

Let me know what you think

### CODE REVIEW

**Comment by sensboston** [comment]
Let me try first before approval. I'm kinda busy now but will do as soon as I get my hands on, OK?

**Comment by FaBjE** [comment]
No problem, Take your time.
I wasn't sure if you had seen these PR.

**Comment by FaBjE** [comment]
Thanks for merging 😄

**Comment by sensboston** [comment]
Thank you for contributing!

**Comment by sensboston** [comment]
@FaBjE, maybe you will find a time to update a **README.md** file to reflect latest changes? I'm thinking to issue and publish a new release (and update app at the MS Store - surprise, it was published a long time ago, and, I believe, it was a very first console app published at the MS Store 😉 )

**Comment by sensboston** [comment]
@FaBjE btw, I've added you as a collaborator to this repo, so you can apply changes without issuing a PRs 😜

**Comment by FaBjE** [comment]
> @FaBjE, maybe you will find a time to update a **README.md** file to reflect latest changes? I'm thinking to issue and publish a new release (and update app at the MS Store - surprise, it was published a long time ago, and, I believe, it was a very first console app published at the MS Store 😉 )

I included an update to readme.md in this PR (trying to) describe all the features.
Did I miss something?



> @FaBjE btw, I've added you as a collaborator to this repo, so you can apply changes without issuing a PRs 😜

Thank you very much 😃  I'm sure you would understand if I say I don't have much time. But I might be able to do some things here and there.

**Pull request merged**
