### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by jpstotz**
Added resolution of BLE read/write errors codes to their error name -> see `ProtocolErrorCode`.

My BLE device had services defined by Bluetooth SIG, but not present in `GattNativeServiceUuid` so I noticed that these services are shown by their number in decimal format not in hex as used by Bluetooth sig. This is now changed.

`GattNativeServiceUuid` was updated to include all service names present in the latest "[Assigned Numbers Document](https://btprodspecificationrefs.blob.core.windows.net/assigned-numbers/Assigned%20Number%20Types/Assigned_Numbers.pdf)". 

Also `GattNativeCharacteristicUuid`.

And finally I added the possibility to select a service or characteristic by it's UUID, no matter if it is a "custom" or not.

### CODE REVIEW

**Comment by sensboston** [comment]
Thanks for contributing but le'me test and review your changes first.

P.S. Next time use GitHub "Reviewers" and "Assigners" menus on the right.

**Comment by jpstotz** [comment]
> Thanks for contributing but le'me test and review your changes first.
No problem take your time. I created the PR mainly as I think my modifications may be of interest to others, too. 

> P.S. Next time use GitHub "Reviewers" and "Assigners" menus on the right.

I am not sure what you are referring to. In this PR the section `Reviewers` only allows me to switch the PR between draft and non-draft mode (this what I did when I noticed that the PR contains bugs and back when I had fixed them).
And the `Assignees` has no functionality I could use.  

@sensboston

**Comment by sensboston** [comment]
@jpstotz , I'm referring to:

in that case my GitHub notification settings will let me know that someone requested action from me 😉

**Comment by jpstotz** [comment]
@sensboston Both sections are only available in issues/PRs that belong to a projects where you have write access. As an just a Contributor without any additional permissions I can't assign you to the PR, even if I am the author of the issue/PR.

**Comment by sensboston** [comment]
OK, I didn't know that.

**Pull request merged**
