### PR TITLE
Added possibility to connect to a device using its bluetooth address

### LINKED ISSUE #27: Feature Request: Connect to device via bluetooth address
Hi,

I have a lot of ble devices with the same advertising name.
It would be cool if there was a way of connecting to them using the 6-byte bluetooth address. At the moment I don't really have a way of differentiating between the devices using just the name.

Other than that its a really helpful application for testing various communication protocls during development.
Thanks for your effort!

### PR DESCRIPTION
**Pull request by UCSIG**
Closes #27 

- I've added checks to determine whether the user provided the device's advertising name or bluetooth address as an argument to the `open` command. If a valid bluetooth address is detected, this address is used to connect to the device.
- The `list` command now also prints the bluetooth address. That way, connectable ble devices which don't advertise their name can also be connected to.
- I've split added two commands called `format_send` and `format_receive`. This way received data can be displayed in multiple different formats while keeping the sending format different. `format_receive` takes a list of parameters like hex, bin, ascii, etc. The regular `format` command still works, it will set the send and receive format to the same value if used.
- I've updated the `help` text to show the newly added options.

### CODE REVIEW

**Comment by UCSIG** [comment]
Hey @sensboston,

did you already have time to look at the pull request?

**Review by sensboston — APPROVED** [review]

**Comment by sensboston** [comment]
Reviewed & merged.

**Comment by sensboston** [comment]
Hey, @UCSIG , could you please take a look to the https://github.com/sensboston/BLEConsole/issues/26 ?
I'm an extremely busy with the other stuff now but I think you can fix that issue really easy?

**Comment by UCSIG** [comment]
@sensboston Yes, I already had a look at #26 and could reproduce the bug. I'm currently pretty busy, but I'll try to get to it as soon as I have some spare time.

**Comment by sensboston** [comment]
Thanks!

**Pull request merged**
